/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type GoogleReview = {
  _id: string;
  _type: "googleReview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: string;
  rating?: number;
  text?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Shop = {
  _id: string;
  _type: "shop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  address?: string;
  phone?: string;
  email?: string;
  mapsUrl?: string;
  hours?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: CategoryReference;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  kicker?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroCtaLabel?: string;
  heroCtaHref?: string;
  universKicker?: string;
  universTitle?: string;
  universIntro?: string;
  universLinkLabel?: string;
  videoFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  videoTitle?: string;
  videoText?: string;
  videoCtaLabel?: string;
  aboutKicker?: string;
  aboutTitle?: string;
  aboutText?: string;
  aboutImageLarge?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  aboutImageSmall?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featuredKicker?: string;
  featuredTitle?: string;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  shopsKicker?: string;
  shopsTitle?: string;
  shopsEmptyText?: string;
  reviewsKicker?: string;
  reviewsTitle?: string;
  reviewsEmptyText?: string;
  reviewsLinkLabel?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  whatsapp?: string;
  phone?: string;
  instagram?: string;
  facebook?: string;
  googleReviewsUrl?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | GoogleReview
  | SanityImageAssetReference
  | Shop
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | Product
  | Slug
  | Category
  | SanityFileAssetReference
  | ProductReference
  | HomePage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/index.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{whatsapp, phone, instagram, facebook, googleReviewsUrl, seoDescription, ogImage}
export type SETTINGS_QUERY_RESULT = {
  whatsapp: string | null;
  phone: string | null;
  instagram: string | null;
  facebook: string | null;
  googleReviewsUrl: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{    heroTitle, heroSubtitle, heroImage, heroCtaLabel, heroCtaHref,    universKicker, universTitle, universIntro, universLinkLabel,    "videoUrl": videoFile.asset->url,    videoPoster, videoTitle, videoText, videoCtaLabel,    aboutKicker, aboutTitle, aboutText, aboutImageLarge, aboutImageSmall,    featuredKicker, featuredTitle,    "featuredProducts": featuredProducts[]->{      title, "slug": slug.current, images,      "categoryTitle": category->title    },    shopsKicker, shopsTitle, shopsEmptyText,    reviewsKicker, reviewsTitle, reviewsEmptyText, reviewsLinkLabel,    seoTitle, seoDescription,    "categories": *[_type == "category"] | order(order asc){      title, "slug": slug.current, kicker, description, image    },    "shops": *[_type == "shop"] | order(order asc){      name, address, phone, email, hours, mapsUrl    },    "reviews": *[_type == "googleReview"] | order(_createdAt desc)[0...6]{      _id, author, rating, text    }  }
export type HOME_QUERY_RESULT = {
  heroTitle: string | null;
  heroSubtitle: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroCtaLabel: string | null;
  heroCtaHref: string | null;
  universKicker: string | null;
  universTitle: string | null;
  universIntro: string | null;
  universLinkLabel: string | null;
  videoUrl: string | null;
  videoPoster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  videoTitle: string | null;
  videoText: string | null;
  videoCtaLabel: string | null;
  aboutKicker: string | null;
  aboutTitle: string | null;
  aboutText: string | null;
  aboutImageLarge: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  aboutImageSmall: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  featuredKicker: string | null;
  featuredTitle: string | null;
  featuredProducts: Array<{
    title: string | null;
    slug: string | null;
    images: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    categoryTitle: string | null;
  }> | null;
  shopsKicker: string | null;
  shopsTitle: string | null;
  shopsEmptyText: string | null;
  reviewsKicker: string | null;
  reviewsTitle: string | null;
  reviewsEmptyText: string | null;
  reviewsLinkLabel: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
    kicker: string | null;
    description: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }>;
  shops: Array<{
    name: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
    hours: string | null;
    mapsUrl: string | null;
  }>;
  reviews: Array<{
    _id: string;
    author: string | null;
    rating: number | null;
    text: string | null;
  }>;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: HOME_SEO_QUERY
// Query: *[_type == "homePage"][0]{seoTitle, seoDescription}
export type HOME_SEO_QUERY_RESULT = {
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    title, description, image,    "products": *[_type == "product" && category._ref == ^._id]      | order(title asc){        title, "slug": slug.current, description, images    }  }
export type CATEGORY_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  products: Array<{
    title: string | null;
    slug: string | null;
    description: string | null;
    images: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
  }>;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: NAV_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(order asc){title, "slug": slug.current}
export type NAV_CATEGORIES_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)]{"slug": slug.current}
export type CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    title, description, images,    "category": category->{title, "slug": slug.current}  }
export type PRODUCT_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
} | null;

// Source: src/sanity/queries/index.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(title asc){title, "slug": slug.current, images, "categoryTitle": category->title}
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  categoryTitle: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && defined(slug.current)]{"slug": slug.current}
export type PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: SHOPS_QUERY
// Query: *[_type == "shop"] | order(order asc){name, address, phone, email, hours, mapsUrl, image}
export type SHOPS_QUERY_RESULT = Array<{
  name: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  hours: string | null;
  mapsUrl: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{whatsapp, phone, instagram, facebook, googleReviewsUrl, seoDescription, ogImage}': SETTINGS_QUERY_RESULT;
    '*[_type == "homePage"][0]{\n    heroTitle, heroSubtitle, heroImage, heroCtaLabel, heroCtaHref,\n\n    universKicker, universTitle, universIntro, universLinkLabel,\n\n    "videoUrl": videoFile.asset->url,\n    videoPoster, videoTitle, videoText, videoCtaLabel,\n\n    aboutKicker, aboutTitle, aboutText, aboutImageLarge, aboutImageSmall,\n\n    featuredKicker, featuredTitle,\n    "featuredProducts": featuredProducts[]->{\n      title, "slug": slug.current, images,\n      "categoryTitle": category->title\n    },\n\n    shopsKicker, shopsTitle, shopsEmptyText,\n\n    reviewsKicker, reviewsTitle, reviewsEmptyText, reviewsLinkLabel,\n\n    seoTitle, seoDescription,\n\n    "categories": *[_type == "category"] | order(order asc){\n      title, "slug": slug.current, kicker, description, image\n    },\n    "shops": *[_type == "shop"] | order(order asc){\n      name, address, phone, email, hours, mapsUrl\n    },\n    "reviews": *[_type == "googleReview"] | order(_createdAt desc)[0...6]{\n      _id, author, rating, text\n    }\n  }': HOME_QUERY_RESULT;
    '*[_type == "homePage"][0]{seoTitle, seoDescription}': HOME_SEO_QUERY_RESULT;
    '*[_type == "category" && slug.current == $slug][0]{\n    title, description, image,\n    "products": *[_type == "product" && category._ref == ^._id]\n      | order(title asc){\n        title, "slug": slug.current, description, images\n    }\n  }': CATEGORY_QUERY_RESULT;
    '*[_type == "category"] | order(order asc){title, "slug": slug.current}': NAV_CATEGORIES_QUERY_RESULT;
    '*[_type == "category" && defined(slug.current)]{"slug": slug.current}': CATEGORY_SLUGS_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug][0]{\n    title, description, images,\n    "category": category->{title, "slug": slug.current}\n  }': PRODUCT_QUERY_RESULT;
    '*[_type == "product"] | order(title asc){title, "slug": slug.current, images, "categoryTitle": category->title}': ALL_PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && defined(slug.current)]{"slug": slug.current}': PRODUCT_SLUGS_QUERY_RESULT;
    '*[_type == "shop"] | order(order asc){name, address, phone, email, hours, mapsUrl, image}': SHOPS_QUERY_RESULT;
  }
}
